<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AprendicesSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'name' => 'Jhan', 
                'last_name' => 'Peña',
                'document_type_id' => 1,
                'number_document' => 1024477349,
                'telephone' => 3922820,
                'phone_number' => 3133033390,
                'address' => 'CLL 62D 75I 53',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2005-10-27',
                'email' => 'jhsbtian962017@gmail.com',
                'password' => 'jhan2710',
                'role_id' => 1
            ],
            [
                'name' => 'Camilo', 
                'last_name' => 'Acevedo',
                'document_type_id' => 1,
                'number_document' => 104578963,
                'telephone' => 3487521,
                'phone_number' => 3156398741,
                'address' => 'CLL 88I 75H',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2006-02-14',
                'email' => 'cami222acev@gmail.com',
                'password' => 'camil222',
                'role_id' => 2
            ],
            [
                'name' => 'Daniel', 
                'last_name' => 'Atara',
                'document_type_id' => 2,
                'number_document' => 102874569,
                'telephone' => 3874552,
                'phone_number' => 314578965,
                'address' => 'CLL 84J 54L',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 3,
                'birthdate' => '2006-05-16',
                'email' => 'dazataras@gmail.com',
                'password' => 'dani27',
                'role_id' => 3
            ],
            [
                'name' => 'Juan', 
                'last_name' => 'Castillo',
                'document_type_id' => 1,
                'number_document' => 106474517,
                'telephone' => 3145782,
                'phone_number' => 3458796321,
                'address' => 'CLL 87D 54G',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2005-01-07',
                'email' => 'jamito@gmail.com',
                'password' => 'juan0701',
                'role_id' => 4
            ],
            [
                'name' => 'Diego', 
                'last_name' => 'Carranza',
                'document_type_id' => 1,
                'number_document' => 178459632,
                'telephone' => 3245874,
                'phone_number' => 31124578963,
                'address' => 'CLL 65H 41Ñ',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2005-04-24',
                'email' => 'diegoca@gmail.com',
                'password' => 'diegoca',
                'role_id' => 1
            ],
            [
                'name' => 'Johanna', 
                'last_name' => 'Sandoval',
                'document_type_id' => 1,
                'number_document' => 1047548745,
                'telephone' => 2145874,
                'phone_number' => 3132417589,
                'address' => 'CLL 65J 41Ñ',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 3,
                'birthdate' => '2006-02-10',
                'email' => 'sandovaljojo@gmail.com',
                'password' => 'joha1002',
                'role_id' => 2
            ],
            [
                'name' => 'Diego', 
                'last_name' => 'Capera',
                'document_type_id' => 1,
                'number_document' => 1024458741,
                'telephone' => 3425879,
                'phone_number' => 331657489,
                'address' => 'CLL 65U 75P',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2006-01-27',
                'email' => 'diegocap@gmail.com',
                'password' => 'capera24',
                'role_id' => 3
            ],
            [
                'name' => 'Peter', 
                'last_name' => 'Bustamante',
                'document_type_id' => 1,
                'number_document' => 1247896521,
                'telephone' => 3245874,
                'phone_number' => 3125478963,
                'address' => 'CLL 24S 54T',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2004-11-25',
                'email' => 'pedrobust@gmail.com',
                'password' => 'peter25',
                'role_id' => 4
            ],
            [
                'name' => 'William', 
                'last_name' => 'Lozano',
                'document_type_id' => 1,
                'number_document' => 11154789632,
                'telephone' => 39547896,
                'phone_number' => 3124587962,
                'address' => 'CLL 25M 47K',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 3,
                'birthdate' => '2004-09-17',
                'email' => 'williamloza@gmail.com',
                'password' => 'willoza',
                'role_id' => 1
            ],
            [
                'name' => 'Cristian', 
                'last_name' => 'Leon',
                'document_type_id' => 1,
                'number_document' => 102547896,
                'telephone' => 3214785,
                'phone_number' => 315698742,
                'address' => 'CLL 58D 25F',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2005-04-19',
                'email' => 'crislion@gmail.com',
                'password' => 'lion19',
                'role_id' => 2
            ],
            [
                'name' => 'Danna', 
                'last_name' => 'Jimenez',
                'document_type_id' => 1,
                'number_document' => 1047896521,
                'telephone' => 395478,
                'phone_number' => 3112547896,
                'address' => 'CLL 98N 21Y',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2006-01-14',
                'email' => 'dannajime@gmail.com',
                'password' => 'jime0',
                'role_id' => 3
            ],
            [
                'name' => 'Maikol', 
                'last_name' => 'Garcia',
                'document_type_id' => 1,
                'number_document' => 102478535,
                'telephone' => 358742,
                'phone_number' => 3121478596,
                'address' => 'CLL 98J 24L',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 3,
                'birthdate' => '2005-12-17',
                'email' => 'mikegar@gmail.com',
                'password' => 'maik17',
                'role_id' => 4
            ],
            [
                'name' => 'Ronald', 
                'last_name' => 'Puerto',
                'document_type_id' => 1,
                'number_document' => 102484569,
                'telephone' => 321456,
                'phone_number' => 3124587963,
                'address' => 'CLL 65I 21L',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2005-08-17',
                'email' => 'ronaldport@gmail.com',
                'password' => 'ronaldo17',
                'role_id' => 1
            ],
            [
                'name' => 'Valentina', 
                'last_name' => 'Avila',
                'document_type_id' => 1,
                'number_document' => 214587963,
                'telephone' => 3914587,
                'phone_number' => 3145879652,
                'address' => 'CLL 54B 21E',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2006-07-05',
                'email' => 'valenavila@gmail.com',
                'password' => 'valen05',
                'role_id' => 2
            ],
            [
                'name' => 'Nicolas', 
                'last_name' => 'Barreto',
                'document_type_id' => 1,
                'number_document' => 1024856971,
                'telephone' => 3124785,
                'phone_number' => 354789632,
                'address' => 'CLL 67L 62 H',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 3,
                'birthdate' => '2005-11-29',
                'email' => 'nicolaquiere@gmail.com',
                'password' => 'microlax',
                'role_id' => 3
            ],
            [
                'name' => 'Brayan', 
                'last_name' => 'Capera',
                'document_type_id' => 1,
                'number_document' => 104896523,
                'telephone' => 3247896,
                'phone_number' => 3132547896,
                'address' => 'CLL 54R 32K',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2006-02-27',
                'email' => 'bradcap@gmail.com',
                'password' => 'bryan2',
                'role_id' => 4
            ],
            [
                'name' => 'Isaac', 
                'last_name' => 'Revelo',
                'document_type_id' => 1,
                'number_document' => 1254786325,
                'telephone' => 33659874,
                'phone_number' => 3124158796,
                'address' => 'CLL 98U 21P',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2006-04-29',
                'email' => 'isaac@gmail.com',
                'password' => 'revman254',
                'role_id' => 1
            ],
            [
                'name' => 'Juan', 
                'last_name' => 'Salgado',
                'document_type_id' => 1,
                'number_document' => 12657894,
                'telephone' => 358746,
                'phone_number' => 316587412,
                'address' => 'CLL 64V 25P',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 3,
                'birthdate' => '2006-10-24',
                'email' => 'juansal@gmail.com',
                'password' => 'salgado241',
                'role_id' => 2
            ],
            [
                'name' => 'Fredy', 
                'last_name' => 'Leyva',
                'document_type_id' => 1,
                'number_document' => 1024476487,
                'telephone' => 3922458,
                'phone_number' => 3133033654,
                'address' => 'CLL 87K 14L',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 1,
                'birthdate' => '2006-05-14',
                'email' => 'fredyley@gmail.com',
                'password' => 'fred45',
                'role_id' => 3
            ],
            [
                'name' => 'Sebastian', 
                'last_name' => 'Triana',
                'document_type_id' => 1,
                'number_document' => 101475124,
                'telephone' => 3785412,
                'phone_number' => 312478569,
                'address' => 'CLL 96I 54B',
                'id_country' => 37,
                'id_department' => 2,
                'id_city' => 2,
                'birthdate' => '2005-11-19',
                'email' => 'sebasmicro@gmail.com',
                'password' => 'micro05',
                'role_id' => 4
            ],
        ];

        foreach ($users as $userData) {
            $user = new User();
            $user->fill($userData);
            $user->password = Hash::make('password');
            $user->save();
        }
    }
    }

